// Import react deps
import React from 'react';
import ReactDOM from 'react-dom';

// CSS generated by Tailwind
import './index.css';
// Custom CSS
import './custom.css';


// Custom components
import App from './App';
import registerServiceWorker from './registerServiceWorker';

ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
